module.exports = {
  extends: ['@commitlint/config-conventional'],
  parserPreset: {
    parserOpts: {
      issuePrefixes: ['#'],
    },
  },
  rules: {
    'subject-case': [0],
    'subject-full-stop': [2, 'always', '.'],
    'header-max-length': [2, 'always', 78],
    'scope-enum': [
      2,
      'always',
      [
        'apds9960',
        'bme280',
        'bq27441',
        'daplink_bridge',
        'daplink_flash',
        'gc9a01',
        'hts221',
        'im34dt05',
        'ism330dl',
        'lis2mdl',
        'mcp23009e',
        'ssd1327',
        'steami_config',
        'vl53l1x',
        'wsen-hids',
        'wsen-pads',
        'ci',
        'docs',
        'style',
        'tests',
        'tooling',
        'steami_screen'
      ],
    ],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'tooling',
      ],
    ],
    'body-max-line-length': [1, 'always', 100],
  },
};
