# MicroPython time module stub — overrides CPython typeshed for Pylance.
from typing import Tuple

def sleep(seconds: float, /) -> None: ...
def sleep_ms(ms: int, /) -> None: ...
def sleep_us(us: int, /) -> None: ...
def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_cpu() -> int: ...
def ticks_diff(ticks1: int, ticks2: int, /) -> int: ...
def ticks_add(ticks: int, delta: int, /) -> int: ...
def time() -> int: ...
def time_ns() -> int: ...
def localtime(secs: int | None = None, /) -> Tuple: ...
def gmtime(secs: int | None = None, /) -> Tuple: ...
def mktime(local_time: Tuple, /) -> int: ...
