#!/usr/bin/env sh
if [ ! -d node_modules ]; then
	echo "Error: node_modules is missing. Run 'make setup' or 'npm install' first."
	exit 1
fi
npx --no-install validate-branch-name && npx --no-install git-precommit-checks && npx --no-install lint-staged
